apiVersion: v1
kind: Service
metadata:
  name: mysql-standalone
spec:
  ports:
    - 
      port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql-standalone
spec:
    selector:
        matchLabels:
            app: mysql
    template:
        metadata:
            labels: {app: mysql}
        spec:
            containers: [{image: 'mysql:5.6', name: mysql-standalone, env: [{name: MYSQL_ROOT_PASSWORD, value: password}, {name: MYSQL_DATABASE, value: db}, {name: MYSQL_USER, value: sa}, {name: MYSQL_PASSWORD, value: password}], ports: [{containerPort: 3306, name: mysql}], volumeMounts: [{name: mysql-persistent-storage, mountPath: /var/lib/mysql}]}]
            volumes: [{name: mysql-persistent-storage, persistentVolumeClaim: {claimName: mysql-pv-claim}}]   
