apiVersion: v1
kind: Service
metadata:
  name: so-app-deploy
spec:
  selector:
    app: spring
  ports:
  - protocol: TCP
    port: 8086
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: so-app-deploy
  labels:
    app: spring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring
        image: arathdeepak/users-mysql
        ports:
        - containerPort: 8086
        livenessProbe:
          httpGet:
            path: /all
            port: 8086
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          initialDelaySeconds: 3
          periodSeconds: 3        
